### ISSUE TITLE
customizing menu bar

### ISSUE THREAD

**Issue by mg64ve** [jam-py/jam-py#130] opened 2019-12-11 08:41 UTC
Hello @platipusica ,

sorry for the silly question, but I do not find in the documentation.
How can I customize the menu bar?
I want to hide items, and group items in the way they are displayed in a cascading drop-down menu.
Do you get my point?
Thanks.
Cheers.

**Comment by platipusica** [comment] 2019-12-11 10:48
Absolutelly

This is mostly done via Visibility option for the Groups, Tables etc.

Plus, the Ordering is done by moving Items Up/Down.  

See https://goo.gl/j81uDW

D.

**Comment by mg64ve** [comment] 2019-12-11 10:58
Ok thanks.
But grouping several menu items into one is possible?
It should be possible because I have seen some examples.
I wonder to know how can I make it?
Thanks.

**Comment by platipusica** [comment] 2019-12-11 12:36
> Ok thanks.
> But grouping several menu items into one is possible?

Correct. Thats what Group is for.


> It should be possible because I have seen some examples.
> I wonder to know how can I make it?

No need to make anything specific, its all made for you. 

> Thanks.

No problem

**Comment by mg64ve** [comment] 2019-12-11 13:39
Ok thanks but still not clear what flags do I need for grouping?

**Comment by platipusica** [comment] 2019-12-11 14:10
I will leave this for @jam-py to reply :)

**Comment by jam-py** [comment] 2019-12-11 15:54
Hello,
You can try to add a create_single_group option to create_menu method in the task client module 

```
task.create_menu($("#menu"), $("#content"), {
        // splash_screen: '<h1 class="text-center">Application</h1>',
        view_first: true,
        create_single_group: true
    });
```
It can help if all elements are in one group.

**Comment by mg64ve** [comment] 2019-12-12 18:12
Ok, thanks @jam-py 
And how to add create_single_group ?

**Comment by jam-py** [comment] 2019-12-13 06:47
You have to select task node in the project tree in the App Builder,
click Client module button, find the line
```
task.create_menu($("#menu"), $("#content"), {
```
and change the code.

Regards

**Comment by mg64ve** [comment] 2019-12-13 13:26
Sorry, I can't find it @jam-py 
I can use find function and find it but manually I can't find it and I can't display the code

**Comment by platipusica** [comment] 2019-12-13 15:02
http://demo.jam-py.com/builder.html#

Task/Client

Line 22

**Comment by mg64ve** [comment] 2019-12-13 16:48
Ok @platipusica now I have found it.
I thought it were a function and it is in reality part of function on_page_loaded(task)
Now it groups me under "Catalogs" label.
This is very nice but it is not exactly what I want to do.
I want make my own groups.
Is there any way to assign a label to each item in the catalogs and make my own grouping?

**Comment by platipusica** [comment] 2019-12-13 16:56
But you can make your own Groups :) As many as you like.

I think you are after a fully customized Menu to your own preferences? Pls explain in a drawing or scratch- many available on the Net, with a Table link to an menu item.

Thx

**Comment by mg64ve** [comment] 2019-12-17 15:52
Hi @platipusica 
If I go to Groups and I try to create a new group, it basically change the name to the selected group (Journals in my case).
How can I avoid this?
Also, can I move items from one group to another? I have created some items and in order to put in a different menu I need to move to a different group. At least this is what I understand so far.

**Comment by platipusica** [comment] 2019-12-17 16:45
Renaming Sound like a bug @jam-py ?

**Comment by jam-py** [comment] 2019-12-18 09:11
Hello

I can't reproduce the bug.
As for moving items I plan do implement it. Now you can't.

Regards

вт, 17 дек. 2019 г. в 19:45, platipusica <notifications@github.com>:

**Comment by mg64ve** [comment] 2019-12-18 09:32
Anyway to do it automatically with JavaScript @jam-py ?

**Comment by jam-py** [comment] 2019-12-18 12:59
Unfortunately, it is impossible.

ср, 18 дек. 2019 г. в 12:32, itresearch <notifications@github.com>:

**Comment by mg64ve** [comment] 2019-12-18 13:20
What about creating objects from a script @jam-py ? Is this batch procedure possible?

**Comment by jam-py** [comment] 2019-12-18 13:43
What objects do you mean?
To change group you have to change parent field value of a record of the
item
in the sys_items table in admin.sqlite database.

ср, 18 дек. 2019 г. в 16:20, itresearch <notifications@github.com>:

**Comment by mg64ve** [comment] 2019-12-18 13:59
Thanks @jam.py I will try.
I mean, is it possible to create a catalog and fields with an external script calling some jam.py API? This would be good in case we need to recreate a project automatically instead of manually with builder.
Do you get my point?

**Comment by jam-py** [comment] 2019-12-19 06:57
Hello
Before trying please make copy of admin.sqlite.
And have in mind that group you are moving item to must have
the save common fields.
As for recreating project automatically you can use export and import
utilities.
Please read
http://jam-py.com/docs/how_to/how_to_migrate_development_to_production.html
http://jam-py.com/docs/how_to/how_to_migrate_to_another_database.html

Regards

ср, 18 дек. 2019 г. в 16:59, itresearch <notifications@github.com>:

**Comment by mg64ve** [comment] 2019-12-25 08:05
Sorry @jam-py , a lot of things to do before Christmas and I didn't have time to look on this.
I have tried to make some manipulations in admin.sqlite database but the result was that I could see menu properly, but I could not see the tables properly anymore.
I will try again with export/import database.
Thanks.

**Comment by jam-py** [comment] 2019-12-25 13:13
It's OK

ср, 25 дек. 2019 г. в 11:05, itresearch <notifications@github.com>:

**Comment by jam-py** [comment] 2019-12-28 13:40
Hello, 

I added possibility to create custom menues using create_menu method.
This is the way you can do it:

```
    let menu = [
            ['First',  [task.invoices, task.customers]],
            ['Second', [task.journals, task.catalogs]],
            [task.reports]
        ];
    task.create_menu($("#menu"), $("#content"), {
        custom_menu: menu,
        splash_screen: '<h1 class="text-center">Jam.py Demo Application</h1>',
        view_first: true,
        create_single_group: false,
        create_group_for_single_item: false
    });

```

Regards

**Comment by mg64ve** [comment] 2019-12-28 15:38
Thanks @jam-py for your effort.
But when I put this in function on_page_loaded(task) it does not display any menu.
Is there anything else I can do?

**Comment by jam-py** [comment] 2019-12-28 16:37
You must add the lines

```

let menu = [
            ['First',  [task.invoices, task.customers]],
            ['Second', [task.journals, task.catalogs]]
        ];

```

where 'First', 'Second' are the names of menu items and
[task.invoices, task.customers]
are items that will be added to these menu items. You can double click on
items in the tack tab to add them.

[image: custom_menu.png]

The old lines wher menu was created must be deleted.
Please, try again. If it fails, open debugger in the browser and send me
the
lines from console.


сб, 28 дек. 2019 г. в 18:38, itresearch <notifications@github.com>:

**Comment by jam-py** [comment] 2019-12-28 16:43
![image](https://user-images.githubusercontent.com/9674777/71546643-4494c100-29aa-11ea-8fea-81700c2dae8e.png)

**Comment by mg64ve** [comment] 2019-12-28 16:52
Thanks @jam-py, it as just a typo. Now it works.
I think you can close this issue.
Thank you very much again.
Cheers.

**Comment by platipusica** [comment] 2019-12-28 19:09
@jam-py 
How would that relate to User permissions?

Also, can we add a Menu separator, like a Submenu to the Menu? Menu Separator might be a Line like this:
-----
or similar.
Thx

**Comment by jam-py** [comment] 2020-01-05 09:59
Hi, @platipusica 

You are right.

I have taken into account user permissions.
Menu separator can be added by adding an empty string and
function can be specifyed that will be executed when menu item clicked

```
    let menu = [
            ['First',  [task.invoices, task.customers]],
            {'Second': [task.details, task.catalogs, '', task.reports]},
            {Third: [task.details, {Params: function() {alert('params clicked')}}]},
            {Fourth: [task.task.analytics, {'Artists list': [task.artists]}]},
            [task.reports],
            task.reports
        ];
    task.create_menu($("#menu"), $("#content"), {
        custom_menu: menu,
        splash_screen: '<h1 class="text-center">Jam.py Demo Application</h1>',
        view_first: true,
        create_single_group: false,
        create_group_for_single_item: false
    });
```

**Comment by platipusica** [comment] 2020-01-13 08:18
Whow!

This is brilliant @jam-py !

Thank you

**Comment by jam-py** [comment] 2020-01-13 09:33
Hi, Dean

What scripting do you mean?

Regards,
Andrew

пн, 13 янв. 2020 г. в 11:18, platipusica <notifications@github.com>:

**Comment by platipusica** [comment] 2020-01-14 03:12
I mean below what we discussed:

"Hi Andrew,

If I may suggest, it would be much easier to write a Python script to do things like this. It would take you no time b/c u know the structure. This is really needed as utilities.

We are using scripting all the time, Im not touching gui for stuff I can do with a script ;)

Regards

D."

:)

**Comment by jam-py** [comment] 2020-01-14 07:09
Hi, @platipusica 

I plan to create actions, menus that can be setup in some designer. 
But it is a big work. I think it is enough for now. 
I want now finish the 6 version.
I will close the issue.

Regards

**Closed by jam-py** 2020-01-14 07:09 UTC
